name: testing

on:
  issue_comment:
    

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "event name is:" ${{ github.event_name }} 
      - run: echo "event type is:" ${{ github.event.action }} 
      - run: echo "Event name:" $GITHUB_EVENT_NAME


        # pull_request:
  #   types: [opened, edited, reopened]